apiVersion: v1
kind: Service
metadata:
  name: {{ template "mlbench.worker.fullname" . }}
  labels:
    app: {{ template "mlbench.name" . }}
    chart: {{ template "mlbench.chart" . }}
    component: "{{ .Values.worker.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    set: default-set
spec:
  selector:
    app: {{ template "mlbench.name" . }}
    release: {{ .Release.Name }}
  clusterIP: None
  ports:
  - name: dummy # Actually, no port is needed.
    port: 1234
    targetPort: 1234